# SPDX-License-Identifier: BSD-3-Clause
# Copyright(c) 2010-2014 Intel Corporation
#

KMOD=	contigmem
SRCS=	contigmem.c device_if.h bus_if.h
CFLAGS = -DRTE_CONTIGMEM_MAX_NUM_BUFS=64 -DRTE_CONTIGMEM_MAX_NUM_DEVS=64 \
	-DRTE_CONTIGMEM_DEFAULT_NUM_DEVS=1 -DRTE_CONTIGMEM_DEFAULT_NUM_BUFS=1 \
	-DRTE_CONTIGMEM_DEFAULT_BUF_SIZE=536870912

.include <bsd.kmod.mk>
